// config/data.js
const empresas = [
    // Universidad de La Frontera (RUT: 87.912.900-1)
    "UNIVERSIDAD DE LA FRONTERA",

    // Personal UFRO
    "Alexander Silva (Dpto. Informática)",
    "Valeria Saldías (Consejo Académico)",
    "Nataly Acuña (UFRO)",
    "Paola Olave (UFRO)",
    "Pedro Anabalón (UFRO)",
    "Noelia Sepúlveda (BIOREN)",
    "Rubén Castro (UFRO)",
    "Patricia Aros (UFRO)",
    "Gissel Peña (Contabilidad)",
    "Manuel Palma (Adquisiciones CODA)",
    "Graciela Retamal (Sría. Dir. Coop. Internacional)",
    "Juan Carlos Sandoval (UFRO)",
    "Patricia Soto (Sría. BIOREN)",
    "Juan C. Oviedo (Dpto. Ing. Sistemas)",
    "Gloria Gacitúa (Informática DDE)",
    "Gloria Cid (Sría. Contraloría)",
    "Mauricio Zamorano (UFRO)",
    "Fernando Huenupan (UFRO)",
    "Cristian Alister (UFRO)",
    "Christian Antileo (UFRO)",
    "Patricia Contreras (UFRO)",
    "Yessica Avendaño (UFRO)",
    "Marcia Zambrano (UFRO)",
    "Jacqueline Trujillo (UFRO)",
    "Claudia Villagrán (Movilidad Estudiantil)",
    "Magdalena Espinoza (Sría. Carrera Psicología)",
    "Alvaro Roa (UFRO)",
    "Lucy Ketterer (UFRO)",
    "Mariano del Sol (UFRO)",
    "Carolina Panisello (UFRO)",
    "Felipe Opazo (Dir. Coord. de Idioma)",
    "Ana Alarcón (Salud Pública)",
    "Patricia Contreras (UFRO)",
    "Mauricio Zambrano (UFRO)",
    "Claudia Sanhueza (Nucleo CS-UFRO)",
    "Camila Henriquez (Dir. Académica Pregrado)",
    "Margarita Contreras (Secretaría IDER)",
    "Jorge Antune (UFRO)",
    "Valeria Jara (Sría. Direc.Instituto Agroindustria)",
    "Guillermo Davinson (Docentes Trabajo Social)",
    "JAVIERA SOLEDAD PARADA CARCAMO",
    "Boris Pavez (Ingeniería Eléctrica)",
    "Gabriela Paineo (Secretaría carrera Obstetricia)",
    "Cyntia Boutaud (UFRO)",
    "Luz Huincaleo (Of.Innovación y Transferencia Tec.)",
    "María Jesús Osses (UFRO)",
    "Valentina Lizama (Instituto Agronindustrias)",
    "Cinthia Torres (Adquisiciones Biblioteca)",
    "Nadia Catalán (Of. Innovación y Transferencia Tec.)",
    "José Gálvez (Docentes Trabajo Social)",
    "Gloria Gacitúa (Ingeniera Informática DDE)",
    "Jacqueline Trujillo (Sría. Decretación)",
    "Julio Tereucan (Docentes Trabajo Social)",
    "Camila Hemríquez (UFRO)",
    "Sandra Villa (Secretaría Morfología)",
    "Francisca Acevedo (UFRO)",
    "MALTEXCO (UFRO)",
    "Gonzalo Tapia (UFRO)",
    "Carolina Panisello (UFRO)",
    "Lorena Cuevas (Agroindustria)",
    "Ignacio Álvarez (Coordinación de Deportes)",
    "Andres Quiroz (Ciencias Quimicas-UFRO)",
    "Andres Concha (Psicologia-UFRO)",
    "Marcia Zambrano (Dpto. Ing. Química)",
    "María Sobarzo (Lab. Suelos Inst. Agroindustria)",
    "Ruth Novoa (Ing. Sistemas)",
    "Jorge Vásquez (Soporte Informático Fac. Medicina)",
    "Patricio Leal (UFRO)",
    "Gloria Gacitúa (Ingeniera Informática DDE)",
    "Pablo Betancourt (Dpto. Odont. Integral)",
    "Flor Maripi (UFRO)",
    "Luz Huincaleo (UFRO)",
    "Miguel Sandoval (UFRO)",
    "Guillermo Davinson (UFRO)",
    "Yessica Avendaño (UFRO)",
    "Joel Parra (UFRO)",
    "Berta Schnettler (UFRO)",
    "Patria Paz (UFRO)",
    "Marco Altamirano (UFRO)",
    "Nelson Quezada (UFRO)",
    "Ana M° Alarcon (Dpto. Salud pública)",
    "Angélica Malanga (Sría. Jefe de Gabinete)",
    "Juan Carlos Sandoval (Encargado de Informática FCJE)",
    "Paula Moreno (UFRO)",
    "Jacqueline Almeyda (UFRO)",

    // Empresas y otros
    "MOLINO BIO BIO S A",
    "CORPORACION EDUCACIONAL SAN BERNARDO",
    "CORPORACION EDUCACIONAL SOCIEDAD EVANGELICA",
    "CONSULTORA ASAYCO SPA",
    "SOCIEDAD DE PROFESIONALES ARQMOSFERA",
    "CLINICA ALEMANA DE TEMUCO S A",
    "HOSTAL PLAZA LAS BANDERAS SPA",
    "Kuden SA",
    "Constructora Garcia",
    "Constructora Luis Saez",
    "SOCIEDAD ODONTOLOGICA CARRILLO Y ROJAS",
    "Odontologos Flores y Pineda",
    "COMUNICACION Y TELEFONIA RURAL S A",
    "APIA SPA",
    "SERVICIOS A TERRENO RODRIGO RIFFO",
    "OH MARKET LIMITADA",

    // Otros nombres
    "GERSON ESTEBAN VALENZUELA",
    "GERSON ESTEBAN VALENZUELA GONZALEZ",
    "Myriam Leon",
    "Mauricio Zambrano",
    "JAVIER MOISES SAAVEDRA MUNOZ",
    "Paola Lavanderos",
    "Johanna Gatica",
    "Waldo Terrile",
    "FABIEN NICOLAS LE BONNIEC",
    "Rubén Castro",
    "Pedro Anabalón",
    "Noelia Sepúlveda",
    "FERNANDA EMILIA PINTO IBIETA",
    "Paula Moreno",
    "Marcela Díaz",
    "Javiera Parada Cárcamo",
    "Guiselle Suazo",
    "Patricia Aros",
    "Gissel Peña",
    "Manuel Palma",
    "Graciela Retamal",
    "Patricia Soto",
    "Alexander Silva",
    "Juan C. Oviedo",
    "Gloria Gacitúa",
    "Gloria Cid",
    "Mauricio Zamorano",
    "Fernando Huenupan",
    "Cristian Alister",
    "Christian Antileo",
    "ALEJANDRO MIRANDA CERPA",
    "Juan Antonio Morales",
    "Patricia Contreras",
    "Alejandro Palma",
    "Yessica Avendaño",
    "Marcia Zambrano",
    "Jacqueline Trujillo",
    "Claudia Villagrán",
    "Magdalena Espinoza",
    "Alvaro Roa",
    "Nataly Acuña",
    "Mariano del Sol",
    "Hector Morales",
    "Carolina Panisello",
    "Miriam Paz Leon",
    "Felipe Opazo",
    "Ana Alarcón",
    "Rodrigo Riffo",
    "Cristina Morales",
    "Jorge Baraona",
    "Molino Bio Bio",
    "Alvaro Rioseco",
    "Pamela Jimenez",
    "Marjorie Reyes",
    "Erick Huencho Figueroa",
    "Daniela Vergara",
    "Alexis Barrientos",
    "Claudia Sanhueza",
    "Camila Henriquez",
    "Margarita Contreras",
    "Jorge Antune",
    "Valeria Jara",
    "Guillermo Davinson",
    "Manuel Tobares",
    "Boris Pavez",
    "PAMELA ALEJANDRA JIMENEZ ETCHEVERRIA",
    "Sebastián Luer",
    "MARIA DE LOS ANGELES ANTIVIL ALVAREZ",
    "Cyntia Boutaud",
    "Luz Huincaleo",
    "Ingrid Viertel",
    "Ana Luengo",
    "María Jesús Osses",
    "Soledad Venegas",
    "Valentina Lizama",
    "Cinthia Torres",
    "Nadia Catalán",
    "José Gálvez",
    "MARIA ANTONIETA RUIZ MUNOZ",
    "Colegio Nuestra Señora del Carmen",
    "Marcela Huanquilef",
    "Julio Tereucan",
    "ALDO GUILLERMO OLATE VINET",
    "Sandra Villa",
    "PAULA SOFIA SALVADORES VIERTEL",
    "Gonzalo Tapia",
    "Lorena Cuevas",
    "Ignacio Álvarez",
    "Juan Mellado",
    "Andres Quiroz",
    "María Sobarzo",
    "Ruth Novoa",
    "Jorge Vásquez",
    "Viviana Letelier",
    "PABLO FRANCISCO MEZA NARVAEZ",
    "Patricio Leal",
    "Rodrigo Riffo",
    "GABRIELA ELIZABETH BRICENO MUNOZ",
    "Flor Maripi",
    "Miguel Sandoval",
    "Joel Parra",
    "Berta Schnettler",
    "Patria Paz",
    "Marco Altamirano",
    "Nelson Quezada",
    "Angélica Malanga",
    "Jacqueline Almeyda",
    "Cristian Rioseco"
];

// Función para obtener un nombre aleatorio
function getNombreAleatorio() {
    const indice = Math.floor(Math.random() * empresas.length);
    return empresas[indice];
}

module.exports = {
    empresas,
    getNombreAleatorio
}; 